name: flutter_file_attributes_example
description: Demonstrates how to use the flutter_file_attributes plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.12
  file_picker: ^5.2.5


  flutter_file_attributes:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

